version: '3.9'

services:
  lib1:
    hostname: cr-lib1
    container_name: customrepo_lib1
    image: customrepo-lib1:${TAG:-latest}
    build:
      context: .
      dockerfile: ./lib1/Dockerfile

  lib2:
    hostname: cr-lib2
    container_name: customrepo_lib2
    image: customrepo-lib2:${TAG:-latest}
    build:
      context: .
      dockerfile: ./lib2/Dockerfile
