version: 2.1

x-remote_docker: &remote_docker
  setup_remote_docker:
    version: 20.10.2
    docker_layer_caching: true

executors:
  small:
    docker:
      - image: cimg/base:stable
    resource_class: small

jobs:
  build_lib1:
    executor: small
    steps:
      - checkout
      - <<: *remote_docker
      - run:
          name: Build Image
          command: |
            docker build \
            -f lib1/Dockerfile \
            -t customrepo/lib1:${CIRCLE_TAG:-latest} \
            .
      - run:
          name: Save Docker image
          command: docker save -o customrepo-lib1.tar customrepo/lib1:${CIRCLE_TAG:-latest}
      - store_artifacts:
          path: ./customrepo-lib1.tar
   
  build_lib2:
    executor: small
    steps:
      - checkout
      - <<: *remote_docker
      - run:
          name: Build Image
          command: |
            docker build \
            -f lib2/Dockerfile \
            -t customrepo/lib2:${CIRCLE_TAG:-latest} \
            .
      - run:
          name: Save Docker image
          command: docker save -o customrepo-lib2.tar customrepo/lib2:${CIRCLE_TAG:-latest}
      - store_artifacts:
          path: ./customrepo-lib2.tar

x-run_on_main_only: &run_on_main_only
  filters:
    branches:
      only: main

workflows:
  version: 2
  standard:
    jobs:
      - build_lib1:
        <<: *run_on_main_only
      - build_lib2:
        <<: *run_on_main_only